# Generated by Django 4.1.7 on 2023-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_department_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo", name="field", field=models.IntegerField(default=2),
        ),
    ]
