# Generated by Django 4.1.7 on 2023-04-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_remove_userinfo_field_userinfo_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="size",),
    ]
