# Generated by Django 4.1 on 2023-08-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=0, max_length=11, verbose_name='书名')),
                ('Price', models.IntegerField(default=0, verbose_name='价格')),
                ('author', models.CharField(default=0, max_length=11, verbose_name='作者')),
                ('Publishing_house', models.CharField(default=0, max_length=11, verbose_name='出版社')),
                ('mobile', models.CharField(default=0, max_length=11, verbose_name='编号(ISBN)')),
                ('coverUrl', models.CharField(default=1, max_length=500, verbose_name='图片链接')),
                ('region', models.CharField(choices=[('A', 'A区'), ('B', 'B区'), ('C', 'C区'), ('D', 'D区')], default='A', max_length=11, verbose_name='区域')),
                ('status', models.SmallIntegerField(choices=[(1, '已借用'), (0, '未借用')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('Student_number', models.CharField(max_length=64, verbose_name='学号')),
                ('Telephone_number', models.CharField(max_length=64, verbose_name='电话号码')),
                ('mailbox', models.CharField(max_length=64, verbose_name='邮箱')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_choices', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=1, verbose_name='级别')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='任务详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbook01.admin', verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbook01.admin', verbose_name='管理员')),
            ],
        ),
    ]
