# Generated by Django 4.1 on 2023-08-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='级别'),
        ),
    ]
