# Generated by Django 4.1 on 2023-08-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0005_alter_prettynum_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='mobile',
            field=models.CharField(default=0, max_length=50, verbose_name='编号(ISBN)'),
        ),
    ]
