# Generated by Django 4.1 on 2023-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0006_alter_prettynum_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已借用'), (0, '未借用')], default=0, verbose_name='状态'),
        ),
    ]
