# Generated by Django 4.1 on 2023-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0010_alter_prettynum_publishing_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mailbox',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=16, verbose_name='用户名'),
        ),
    ]
