# Generated by Django 4.1 on 2023-08-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0011_remove_userinfo_mailbox_alter_userinfo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
    ]
