# Generated by Django 4.1 on 2023-08-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0012_rename_name_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='Student_number',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='Telephone_number',
        ),
    ]
