# Generated by Django 4.1 on 2023-08-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0013_remove_userinfo_student_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
