# Generated by Django 4.1 on 2023-09-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0014_remove_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32, verbose_name='日期')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('BookName', models.CharField(max_length=32, verbose_name='书籍名称')),
                ('give', models.SmallIntegerField(choices=[(1, '已归还'), (0, '未归还')], default=0, verbose_name='是否归还')),
            ],
        ),
    ]
