# Generated by Django 4.1 on 2023-09-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0015_lending'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='mobile',
            field=models.CharField(default=0, max_length=64, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='BookName',
            field=models.CharField(max_length=200, verbose_name='书籍名称'),
        ),
    ]
