# Generated by Django 4.1 on 2023-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0016_lending_mobile_alter_lending_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='give',
            field=models.IntegerField(choices=[(1, '已归还'), (0, '未归还')], default=0, verbose_name='是否归还'),
        ),
    ]
