# Generated by Django 4.1 on 2023-09-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0017_alter_lending_give'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='name',
            new_name='username',
        ),
    ]
