# Generated by Django 4.1 on 2023-09-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0018_rename_name_lending_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='author',
            field=models.CharField(default=23, max_length=32, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
