# Generated by Django 4.1 on 2023-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbook01', '0019_lending_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('moderator', '版主')], default='admin', max_length=16, verbose_name='角色'),
        ),
    ]
