# Generated by Django 4.1 on 2023-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("sex", models.BooleanField(default=1)),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("class_null", models.CharField(max_length=5)),
            ],
            options={
                "db_table": "tb_student",
            },
        ),
    ]
