# Generated by Django 4.1 on 2023-07-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfdemo", "0003_alter_student_age_alter_student_class_null_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生"},
        ),
        migrations.AddField(
            model_name="student",
            name="description",
            field=models.TextField(default=13, max_length=1000, verbose_name=""),
            preserve_default=False,
        ),
    ]
