# Generated by Django 4.1 on 2023-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drfdemo", "0004_alter_student_options_student_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="描述"),
        ),
    ]
