# Generated by Django 4.1.7 on 2023-04-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.admin",
                verbose_name="负责人",
            ),
            preserve_default=False,
        ),
    ]
