# Generated by Django 4.1.7 on 2023-04-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0010_city"),
    ]

    operations = [
        migrations.RenameField(model_name="city", old_name="age", new_name="count",),
    ]
